name: Build
on:
  push:
    branches: [ master ]
jobs:
  checkout-and-prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Create workspace
        run: mkdir workspace
      - uses: actions/checkout@v3
        with:
          path: workspace/openp1
      - name: Change Owner of Container Working Directory
        run: chown -R 1001:1001 $GITHUB_WORKSPACE/workspace

  container-test-job:
    needs: checkout-and-prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/zephyr-build:latest
      options: --cpus 1
      volumes:
        - workspace:/workdir
    steps:
      - name: West init 
        run: west init
      - name: West update 
        run: west update
      - name: Build something
        run: west build -b nrf52840dongle_nrf52840
