name: Build
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/zephyr-build:latest
      options: --cpus 1
    steps:
      - name: Test
        run: ls
