name: Build
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.0
      options: --cpus 1
    steps:
      - name: Find cmake
        run: find /root
      - name: Cat cmake
        run: cat /root/.cmake/packages/Zephyr-sdk/*
      - uses: actions/checkout@v3
        with:
          path: zephyr_workspace/openp1
      - name: West init 
        run: west init -l openp1
        working-directory: zephyr_workspace
      - name: West update 
        run: west update
        working-directory: zephyr_workspace
      - name: Build something
        # Workaround issue with SDK not being found
        env: 
          ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.16.0/
        run: west build -b nrf52840dongle_nrf52840 openp1/firmware
        working-directory: zephyr_workspace