name: Build
on:
  push:
    branches: [ master ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/zephyr-build:latest
      options: --cpus 1
    steps:
      - name: Build something
        run: west build -b nrf52840dongle_nrf52840
